backend/api/urls.py
from django.conf.urls import url

from .battles.endpoints import (
    BattleDetailEndpoint,
    CreateBattleEndpoint,
    OngoingBattlesListEndpoint,
    SelectOpponentTeamEndpoint,
    SettledBattlesListEndpoint,
)
from .pokemon.endpoints import ListPokemons
from .users.endpoints import OpponentsList, UserAuthenticatedEndpoint


urlpatterns = [
    # battles' urls
    url(r"^battles/create/$", CreateBattleEndpoint.as_view(), name="create-battle"),
    url(
        r"^battles/select-team/(?P<pk>[-\w]+)/$",
        SelectOpponentTeamEndpoint.as_view(),
        name="select-team",
    ),
    url(r"^battles/settled/$", SettledBattlesListEndpoint.as_view(), name="settled-battles-list"),
    url(r"^battles/ongoing/$", OngoingBattlesListEndpoint.as_view(), name="ongoing-battles-list"),
    url(r"^battles/(?P<pk>[-\w]+)/$", BattleDetailEndpoint.as_view(), name="battle-detail"),
    # users urls
    url(r"^users/authenticated/$", UserAuthenticatedEndpoint.as_view(), name="user-authenticated"),
    url(r"^users/opponents/$", OpponentsList.as_view(), name="opponents-list"),
    # pokemon's urls
    url(r"^pokemon/list/$", ListPokemons.as_view(), name="pokemon-list"),
]

backend/battles/urls.py
from django.conf.urls import url

from .views import (
    BattleDetailView,
    CreateBattleView,
    OnGoingBattlesListView,
    SelectOpponentTeamView,
    SettledBattlesListView,
)


app_name = "battles"

urlpatterns = [
    url(r"^create/$", CreateBattleView.as_view(), name="create-battle"),
    url(r"^select-team/(?P<pk>[-\w]+)/$", SelectOpponentTeamView.as_view(), name="select-team"),
    url(r"^settled/$", SettledBattlesListView.as_view(), name="settled-battles-list"),
    url(r"^ongoing/$", OnGoingBattlesListView.as_view(), name="ongoing-battles-list"),
    url(r"^(?P<pk>[-\w]+)/$", BattleDetailView.as_view(), name="battle-detail"),
]

backend/battles/models.py
from django.db import models

from pokemon.models import Pokemon
from users.models import User


STATUS_CHOICES = [("ONGOING", "ONGOING"), ("SETTLED", "SETTLED")]


class Battle(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="battles_as_creator")
    opponent = models.ForeignKey(User, on_delete=models.CASCADE, related_name="battles_as_opponent")
    status = models.CharField(choices=STATUS_CHOICES, default="ONGOING", max_length=20, blank=True)
    winner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="won_battles", null=True
    )

    def __str__(self):
        return f"Battle #{self.id}: {self.creator.email} X {self.opponent.email}"


class BattleTeam(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="teams")

    pokemon_1 = models.ForeignKey(Pokemon, on_delete=models.CASCADE, related_name="+")
    pokemon_2 = models.ForeignKey(Pokemon, on_delete=models.CASCADE, related_name="+")
    pokemon_3 = models.ForeignKey(Pokemon, on_delete=models.CASCADE, related_name="+")

    battle = models.ForeignKey(Battle, on_delete=models.CASCADE, related_name="teams")

    def __str__(self):
        creator_name = self.creator.email.split("@")[0]
        return f"{creator_name}'s Battle {self.battle.id} Team"

backend/battles/forms.py
from django import forms

from dal import autocomplete

from pokemon.helpers import (
    are_pokemon_positions_repeated,
    pokemon_sum_valid,
    repeated_pokemon_in_teams,
)
from pokemon.models import Pokemon
from users.models import User

from .models import Battle, BattleTeam


POSITION_CHOICES = [(1, 1), (2, 2), (3, 3)]


class AutocompletePokemonForm(forms.ModelForm):
    pokemon_1_position = forms.ChoiceField(choices=POSITION_CHOICES, label="Pokemon position")
    pokemon_2_position = forms.ChoiceField(choices=POSITION_CHOICES, label="Pokemon position")
    pokemon_3_position = forms.ChoiceField(choices=POSITION_CHOICES, label="Pokemon position")
    pokemon_1 = forms.ModelChoiceField(
        label="Pokemon",
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(
            url="pokemon-autocomplete",
            attrs={  # noqa
                "data-placeholder": "Autocomplete pokemon",
                "data-minimum-input-length": 3,
                "data-html": True,
            },
        ),
        required=True,
    )
    pokemon_2 = forms.ModelChoiceField(
        label="Pokemon",
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(
            url="pokemon-autocomplete",
            attrs={  # noqa
                "data-placeholder": "Autocomplete pokemon",
                "data-minimum-input-length": 3,
                "data-html": True,
            },
        ),
        required=True,
    )
    pokemon_3 = forms.ModelChoiceField(
        label="Pokemon",
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(
            url="pokemon-autocomplete",
            attrs={  # noqa
                "data-placeholder": "Autocomplete pokemon",
                "data-minimum-input-length": 3,
                "data-html": True,
            },
        ),
        required=True,
    )

    def clean(self):
        cleaned_data = super().clean()

        if are_pokemon_positions_repeated(self.cleaned_data):
            raise forms.ValidationError("Each Pokemon must have a unique position.")

        is_pokemon_sum_valid = pokemon_sum_valid(
            [
                self.cleaned_data["pokemon_1"],
                self.cleaned_data["pokemon_2"],
                self.cleaned_data["pokemon_3"],
            ]
        )

        if not is_pokemon_sum_valid:
            raise forms.ValidationError("The sum of the Pokemon points can't be greater than 600.")

        return cleaned_data


class CreateBattleForm(AutocompletePokemonForm):
    class Meta:
        model = Battle
        fields = [
            "opponent",
            "pokemon_1",
            "pokemon_1_position",
            "pokemon_2",
            "pokemon_2_position",
            "pokemon_3",
            "pokemon_3_position",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["opponent"].queryset = User.objects.exclude(id=self.initial["creator_id"])


class SelectOpponentTeamForm(AutocompletePokemonForm):
    class Meta:
        model = BattleTeam
        fields = [
            "pokemon_1",
            "pokemon_1_position",
            "pokemon_2",
            "pokemon_2_position",
            "pokemon_3",
            "pokemon_3_position",
        ]

    def clean(self):
        cleaned_data = super().clean()
        pokemon = [
            self.cleaned_data["pokemon_1"],
            self.cleaned_data["pokemon_2"],
            self.cleaned_data["pokemon_3"],
        ]

        if repeated_pokemon_in_teams(pokemon, self.initial["battle"]):
            raise forms.ValidationError("You chose a Pokemon from your opponent's team. Try again.")

        return cleaned_data

backend/battles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.html import format_html
from django.views import generic

from pokemon.helpers import sort_pokemon_in_correct_position

from .forms import CreateBattleForm, SelectOpponentTeamForm
from .models import Battle, BattleTeam
from .tasks import run_battle_and_send_result_email
from .utils.battle import get_round_winner
from .utils.email import send_opponent_battle_invitation_email


class CreateBattleView(LoginRequiredMixin, generic.CreateView):
    model = Battle
    # template_name = "battles/create_battle.html"
    template_name = "react_templates/create_battle.html"

    form_class = CreateBattleForm
    success_url = reverse_lazy("battles:create-battle")

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.status = "ONGOING"
        form.instance.save()

        pokemon = sort_pokemon_in_correct_position(form.cleaned_data)

        BattleTeam.objects.create(creator=self.request.user, battle=form.instance, **pokemon)

        send_opponent_battle_invitation_email(form.instance)

        success_message = format_html(
            f"<h5>Your battle against <b>{form.instance.opponent}</b> was created!</h5>"
            f"<div>Round 1: <b>{pokemon.get('pokemon_1').name}</b> - Attack: \
            {pokemon.get('pokemon_1').attack} | Defense: {pokemon.get('pokemon_1').defense} \
            | HP: {pokemon.get('pokemon_1').hp}</div>"
            f"<div>Round 2: <b>{pokemon.get('pokemon_2').name}</b> - Attack: \
            {pokemon.get('pokemon_2').attack} | Defense: {pokemon.get('pokemon_2').defense} \
            | HP: {pokemon.get('pokemon_2').hp}</div>"
            f"<div>Round 3: <b>{pokemon.get('pokemon_3').name}</b> - Attack: \
            {pokemon.get('pokemon_3').attack} | Defense: {pokemon.get('pokemon_3').defense} \
            | HP: {pokemon.get('pokemon_3').hp}</div>"
            f"<div style='margin-top: 10px;'>Now wait for your opponent to fight back!</div>"
        )
        messages.success(self.request, success_message)

        return super().form_valid(form)

    def get_initial(self):
        return {"creator_id": self.request.user.id}


class SelectOpponentTeamView(LoginRequiredMixin, generic.CreateView):
    # template_name = "battles/select_opponent_team.html"
    template_name = "react_templates/select_opponent_team.html"
    model = BattleTeam
    form_class = SelectOpponentTeamForm

    def get_battle(self):
        return get_object_or_404(
            Battle, opponent=self.request.user, status="ONGOING", pk=self.kwargs["pk"]
        )

    def get_initial(self):
        super(SelectOpponentTeamView, self).get_initial()
        self.initial = {"battle": self.get_battle()}
        return self.initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["battle"] = self.get_battle()
        context["page_title"] = f"Select Battle #{context['battle'].id} Team"
        return context

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.battle = self.get_battle()

        pokemon = sort_pokemon_in_correct_position(form.cleaned_data)

        form.instance.pokemon_1 = pokemon["pokemon_1"]
        form.instance.pokemon_2 = pokemon["pokemon_2"]
        form.instance.pokemon_3 = pokemon["pokemon_3"]

        form.instance.save()
        run_battle_and_send_result_email.delay(form.instance.battle.id)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("battles:battle-detail", args=(self.kwargs["pk"],))


class SettledBattlesListView(LoginRequiredMixin, generic.ListView):
    # template_name = "battles/settled_battles_list.html"
    template_name = "react_templates/settled_battles_list.html"
    model = Battle

    def get_queryset(self):
        queryset = Battle.objects.filter(status="SETTLED").filter(
            Q(creator=self.request.user) | Q(opponent=self.request.user)
        )
        return queryset


class OnGoingBattlesListView(LoginRequiredMixin, generic.ListView):
    # template_name = "battles/on_going_battles_list.html"
    template_name = "react_templates/ongoing_battles_list.html"
    model = Battle

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["battles_i_created"] = (
            Battle.objects.filter(status="ONGOING")
            .filter(creator=self.request.user)
            .order_by("timestamp")
        )
        context["battles_im_invited"] = (
            Battle.objects.filter(status="ONGOING")
            .filter(opponent=self.request.user)
            .order_by("timestamp")
        )
        return context


class BattleDetailView(LoginRequiredMixin, generic.DetailView):
    # template_name = "battles/battle_details.html"
    template_name = "react_templates/battle_details.html"
    model = Battle

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        creator_team = BattleTeam.objects.get(creator=self.object.creator, battle=self.object)

        opponent_team = BattleTeam.objects.filter(
            battle=self.object, creator=self.object.opponent
        ).first()

        context["creator_team"] = [
            creator_team.pokemon_1,
            creator_team.pokemon_2,
            creator_team.pokemon_3,
        ]

        if opponent_team:
            context["opponent_team"] = [
                opponent_team.pokemon_1,
                opponent_team.pokemon_2,
                opponent_team.pokemon_3,
            ]

            winners = []

            for creator_pokemon, opponent_pokemon in zip(
                context["creator_team"], context["opponent_team"]
            ):
                winners.append(get_round_winner(creator_pokemon, opponent_pokemon))

            context["matches"] = zip(
                [1, 2, 3], context["creator_team"], context["opponent_team"], winners
            )
        return context

backend/templates/battles/battle_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PokeBattle{% endblock %}

{% block body %}
<div class="pk-container battle-detail">
  {% include "includes/title.html" with title="Battle Details" %}
  <div class="content">
    <h4>Battle #{{battle.id}} Information</h4>
    <div class="battle-info-container">
      <h5 class="pokemon-font">Status</h5>
      <div class="subtitle pokemon-font">{{battle.status}}!</div>
    </div>
    <div class="battle-info-container">
      <h5 class="pokemon-font">Players</h5>
      <div class="subtitle">
        <span>{{battle.creator.email}}</span> challenged <span>{{battle.opponent.email}}</span> on this battle!
      </div>
    </div>
    {% if user == battle.opponent and battle.winner is None %}
    <div class="battle-team-container">
      <a href="{% url 'battles:select-team' battle.pk %}">
        <div class="pk-btn">Fight back!</div>
      </a>
    </div>
    {% endif %}
    {% if battle.winner is not None %}
    <div class="battle-info-container">
      <h5 class="pokemon-font">Winner</h5>
      <div class="subtitle">
        This battle's winner is <span>{{battle.winner}}</span>.
      </div>
    </div>
    {% endif %}
  </div>
  
  <div class="content">
    {% if battle.winner is not None or user == battle.creator %}
    <h4>Battle #{{battle.id}} Details</h4>
    <div class="battle-info-container">
      <h7 class="pokemon-font">{{battle.creator.email}}'s team</h7>
      <div class="battle-team-container">
        {% for pokemon in creator_team %}
        <div class="pokemon-info-container">
          <div class="pokemon-icon">
            <img src="{{pokemon.img_url}}" height="90px"></img>
          </div>
          <div class="pokemon-name">{{pokemon.name}}</div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    {% if battle.winner is not None %}
    <div class="battle-info-container">
      <h7 class="pokemon-font">{{battle.opponent.email}}'s team</h7>
      <div class="battle-team-container">
        {% for pokemon in opponent_team %}
        <div class="pokemon-info-container">
          <div class="pokemon-icon">
            <img src="{{pokemon.img_url}}" height="80px"></img>
          </div>
          <div class="pokemon-name">{{pokemon.name}}</div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="battle-info-container">
      <h5 class="pokemon-font">Matches</h5>
      {% for i, c_pokemon, o_pokemon, winner in matches %}
      <div class="match">
        <h6 class="pokemon-font">Round #{{i}}</h6>
        <div class="round-info-container">
          {% include 'includes/pokemon_card.html' with pokemon=c_pokemon winner=winner %}
          <div class="vs pokemon-font">VS</div>
          {% include "includes/pokemon_card.html" with pokemon=o_pokemon winner=winner %}
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

backend/templates/battles/create.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}PokeBattle - Create Battle{% endblock %}

{% block body %}
<div class='create-battle'>
  <h1>Create Battle</h1>
  {% if form.errors %}
    {% for error in form.non_field_errors %}
      <p class="error">{{error}}</p>
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    Choose your opponent:
    {% render_field form.opponent %}
    <button type='submit'>Battle!</button>
  </form>
</div>
{% endblock %}

backend/templates/battles/create_battle.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}PokeBattle - Create Battle{% endblock %}

{% block body %}
<div class='pk-container create-battle'>
  {% include "includes/title.html" with title="Create Battle" %}
  {% if form.errors %}
    {% for error in form.non_field_errors %}
      <div class="error">{{error}}</div>
    {% endfor %}
  {% endif %}
  <div class='content'>
    {% for message in messages %}
      <div class="messages">
        {{message}}
      </div>
    {% endfor %}

    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="battle-form-field">
          <span>{{ field.label }}: </span>
          {% render_field field %}
          <span class="field-error">{{ field.errors }}</span>
        </div>
      {% endfor %}
      <div class="btn-container">
        <button class="pk-btn" type="submit">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
<!-- JQuery -->
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

backend/templates/battles/on_going_battles_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}PokeBattle - Ongoing Battles{% endblock %}

{% block body %}
<div class="pk-container ongoing-battles">
    {% include "includes/title.html" with title="Ongoing Battles" %}
    <div class="content">
        <div class="battle-list">
            <h4>Battles waiting for me</h4>
            {% if battles_im_invited.all %}
                {% for battle in battles_im_invited %}
                    <a href="{% url 'battles:battle-detail' battle.pk %}">
                        <div class="list-item">
                            <div>
                                <h6 class="pokemon-font">Battle #{{battle.id}}</h6>
                                <div>
                                    <span class="list-attribute">{{battle.creator}}</span>  challenged you on {{battle.timestamp|date:"d/m/Y"}} at {{battle.timestamp|time:"H:i"}}. Fight back!
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <div>Ops, there's no battles yet!</div>
            {% endif %}
        </div>
        <div class="battle-list">
            <h4>Battles waiting for my opponent</h4>
            {% if battles_i_created.all %}
                {% for battle in battles_i_created %}
                    <a href="{% url 'battles:battle-detail' battle.pk %}">
                        <div class="list-item">
                            <div>
                                <h6 class="pokemon-font">Battle #{{battle.id}}</h6>
                                <div>
                                    <span class="list-attribute">Players</span> {{battle.creator}} VS {{battle.opponent}}
                                </div>
                                <div>
                                    <span class="list-attribute">Time</span> {{battle.timestamp}}
                                </div>
                            </div>
                            <!-- <div class="pk-small-btn">Fight back!</div> -->
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <div>Ops, there's no battles yet!</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

backend/templates/battles/select_opponent_team.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}PokeBattle - Select Team{% endblock %}

{% block body %}
<div class='pk-container create-battle'>
  {% include "includes/title.html" with title=page_title %}
  {% if form.errors %}
    {% for error in form.non_field_errors %}
      <div class="error">{{error}}</div>
    {% endfor %}
  {% endif %}
  <div class='content'>
    {% for message in messages %}
      <div class="messages">
        {{message}}
      </div>
    {% endfor %}
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="battle-form-field">
          <span>{{ field.label }}: </span>
          {% render_field field %}
          <span class="field-error">{{ field.errors }}</span>
        </div>
      {% endfor %}
      <div class="btn-container">
        <button class="pk-btn" type="submit">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
<!-- JQuery -->
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

backend/templates/battles/settled_battles_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}PokeBattle - Settled Battles{% endblock %}

{% block body %}
<div class="pk-container settled-battles">
    {% include "includes/title.html" with title="Settled Battles" %}
    <div class="content">
        <div class="battle-list">
            {% if object_list.all %}
                {% for battle in object_list %}
                <a href="{% url 'battles:battle-detail' battle.pk %}">
                    <div class="list-item settled-battle-item">
                        <div>
                            <h6 class="pokemon-font">Battle #{{battle.id}}</h6>
                            <div>
                                <span class="list-attribute">Players</span> {{battle.creator}} VS {{battle.opponent}}
                            </div>
                            <div>
                                <span class="list-attribute">Winner</span> {{battle.winner}}
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            {% else %}
                <h4>Ops, there's no settled battles yet!</h4>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}