backend/api/urls.py
from django.conf.urls import url

from .battles.endpoints import (
    BattleDetailEndpoint,
    CreateBattleEndpoint,
    OngoingBattlesListEndpoint,
    SelectOpponentTeamEndpoint,
    SettledBattlesListEndpoint,
)
from .pokemon.endpoints import ListPokemons
from .users.endpoints import OpponentsList, UserAuthenticatedEndpoint


urlpatterns = [
    # battles' urls
    url(r"^battles/create/$", CreateBattleEndpoint.as_view(), name="create-battle"),
    url(
        r"^battles/select-team/(?P<pk>[-\w]+)/$",
        SelectOpponentTeamEndpoint.as_view(),
        name="select-team",
    ),
    url(r"^battles/settled/$", SettledBattlesListEndpoint.as_view(), name="settled-battles-list"),
    url(r"^battles/ongoing/$", OngoingBattlesListEndpoint.as_view(), name="ongoing-battles-list"),
    url(r"^battles/(?P<pk>[-\w]+)/$", BattleDetailEndpoint.as_view(), name="battle-detail"),
    # users urls
    url(r"^users/authenticated/$", UserAuthenticatedEndpoint.as_view(), name="user-authenticated"),
    url(r"^users/opponents/$", OpponentsList.as_view(), name="opponents-list"),
    # pokemon's urls
    url(r"^pokemon/list/$", ListPokemons.as_view(), name="pokemon-list"),
]

backend/battles/urls.py
from django.conf.urls import url

from .views import (
    BattleDetailView,
    CreateBattleView,
    OnGoingBattlesListView,
    SelectOpponentTeamView,
    SettledBattlesListView,
)


app_name = "battles"

urlpatterns = [
    url(r"^create/$", CreateBattleView.as_view(), name="create-battle"),
    url(r"^select-team/(?P<pk>[-\w]+)/$", SelectOpponentTeamView.as_view(), name="select-team"),
    url(r"^settled/$", SettledBattlesListView.as_view(), name="settled-battles-list"),
    url(r"^ongoing/$", OnGoingBattlesListView.as_view(), name="ongoing-battles-list"),
    url(r"^(?P<pk>[-\w]+)/$", BattleDetailView.as_view(), name="battle-detail"),
]

backend/templates/base.html
{% load render_bundle from webpack_loader %}
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" />

  <!-- Webpack rendered CSS -->
  {% render_bundle 'main' 'css' %}
</head>

<body>
  <!-- {% include 'includes/sentry_init.html' %} -->
  {% include 'includes/navbar.html' %}

  <!-- Body Content -->
  <div class='block-body'>
    {% block body %}{% endblock %}
  </div>

  <!-- {% include 'includes/footer.html' %} -->

  <!-- django-js-reverse -->
  <script src="{% url 'js_reverse' %}" type="text/javascript"></script>

  <!-- Webpack rendered Javascript -->
  {% render_bundle 'vendors~main' 'js' 'DEFAULT' %} {% render_bundle 'main' 'js' 'DEFAULT' %}
  {% block scripts %}{% endblock %}
</body>
</html>

backend/templates/home.html
{% extends 'base.html' %}

{% block title %}PokeBattle{% endblock %}

{% block body %}
<div class="pk-container">
    <div class="pk-title">Hello, player!</div>
    <div class="pk-subtitle">What do you want to do?</div>
    <div class="content">
        <div class="battle-btn-container">
            <a href="{% url 'battles:create-battle' %}">
                <div class="pk-btn">Battle!</div>
            </a>
            <a href="{% url 'battles:ongoing-battles-list' %}">
                <div class="pk-btn">See ongoing battles</div>
            </a>
            <a href="{% url 'battles:settled-battles-list' %}">
                <div class="pk-btn">See settled battles</div>
            </a>
            <a href="{% url 'invite-user' %}">
                <div class="pk-btn">Invite user</div>
            </a>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/invite_user.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}PokeBattle - Invite User{% endblock %}

{% block body %}
<div class='pk-container create-battle'>
  {% include "includes/title.html" with title="Invite User" %}
  {% if form.errors %}
    {% for error in form.non_field_errors %}
      <div class="error">{{error}}</div>
    {% endfor %}
  {% endif %}
  <div class='content'>
    {% for message in messages %}
      <div class="messages">
        {{message}}
      </div>
    {% endfor %}

    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="battle-form-field">
          <span>{{ field.label }}: </span>
          {% render_field field %}
          {{ field.errors }}
        </div>
      {% endfor %}
      <div class="btn-container">
        <button class="pk-btn" type="submit">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}